services:
  regmanagerbot:
    build:
      context: .  #  Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Path to the Dockerfile relative to the context
    container_name: regmanagerbot
    user: "1000:1000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    restart: on-failure
    command: ["sh", "-c", "sleep 10 && python -m regmanagerbot"]

# services:
#   regmanagerbot:
#     image: janzbff/regmanagerbot:latest
#     container_name: regmanagerbot
#     user: "1000:1000"
#     volumes:
#       - ./logs:/app/logs
#       - ./data:/app/data
#     env_file:
#       - .env   #  使用 .env 文件设置环境变量
#     restart: on-failure